name: synthoseis
channels:
  - conda-forge
  - plotly
  - defaults
dependencies:
  - h5py
  - matplotlib
  - numpy
  - python=3.12.4
  - scikit-image
  - scipy
  - tqdm
  - pytables
  - plotly
  - pip:
    - bruges
    - noise
